### ISSUE TITLE
Measurement Unit Conversion not working after 4.x.x upgrade

### ISSUE THREAD

**Issue by thresholdpeople** [biati-digital/alfred-calculate-anything#112]
Hello,

After upgrading to the latest - 4.0.1 - version, unit conversion stopped working for me.  For example if I write `1300mm to in` all I get in Alfred are options to search via web browser.

The behavior is the same for 4.0.0.  

Going back to 3.5.0 restores original functionality.

(as a feature request, I'd also love to be able to set the amount of decimal places which appear from the conversion as I now see is possible in v4 with currency)

Thanks for all your work.

Boris

**Comment by biati-digital** [comment]
As you don't post any info i guess your problem is related to [#104 comment](https://github.com/biati-digital/alfred-calculate-anything/issues/104#issuecomment-1480883978) An update has been released, you should be able to update directly from Alfred or download the latest update from the [releases page](https://github.com/biati-digital/alfred-calculate-anything/releases)

If this does not fix your problem please open a new issue and use the Bug report template.
