### ISSUE TITLE
Ounces missing from Volume Unit

### ISSUE THREAD

**Issue by mikedvzo** [biati-digital/alfred-calculate-anything#41]
There is no Fluid ounce unit for volume which is essential.

**Comment by yamyoume** [comment]
![image](https://user-images.githubusercontent.com/31030392/124257926-b854e400-dae1-11eb-86a8-178a5395edad.png)
do you have the latest workflow installed, this was added recently

**Comment by mikedvzo** [comment]
Thanks for some reason the workflow said I was up to date so I downloaded the latest from GitHub. On another note it looks like VAT does not support fractional numbers.





--
Mike DiVincenzo
919-741-8314 (Mobile)
919-200-0638 (Home)

**Comment by yamyoume** [comment]
what do you mean fractional numbers, btw I posted an issue about vat , and I've kinda fixed it my self 
you can do the same if you want a quick fix

**Comment by mikedvzo** [comment]
The tax is 7.25% and although I set the value of VAT to 7.25 it is rounding to the nearest whole number 7.

--
Mike DiVincenzo
919-741-8314 (Mobile)
919-200-0638 (Home)

**Comment by yamyoume** [comment]
oh yeah, same problem, I posted the issue here: https://github.com/biati-digital/alfred-calculate-anything/issues/40
and I fixed it myself, it's easy just a couple of changes in the code 
if you want to get to the files:
double click VAT and click on this button 
![image](https://user-images.githubusercontent.com/31030392/124332342-1d422580-db46-11eb-843d-6584cd47ae19.png)

![image](https://user-images.githubusercontent.com/31030392/124332359-28955100-db46-11eb-934e-8e60289e8f00.png)

**Comment by mikedvzo** [comment]
Thanks, I saw your issue on GitHub and updated vat.php and all is good 🙂

Have a good weekend

--
Mike DiVincenzo
919-741-8314 (Mobile)
919-200-0638 (Home)
