### ISSUE TITLE
Updated PHP but still can't use workflow on Mojave

### ISSUE THREAD

**Issue by mrevtai** [biati-digital/alfred-calculate-anything#73]
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?**
Yes, using version 3.5.0

**Describe the bug**
When attempting to activate the workflow by using the "ca" command, I am still receiving an error indicating I need to upgrade my version of PHP, despite it already being upgraded and symlinked through brew. It is specifically looking somewhere in the Application Support folder/workflow itself(?), but I have not experienced this type of issue and am unsure how to correct it.

Is there another path that must be added to my config files? Or something to edit directly within the workflow itself? 

Any help is appreciated, thanks!

**To Reproduce**
1. Open Alfred
1. Type 'ca'
2. Nothing is activated/recognized due to PHP version error (see included info)

**Expected behavior**
Expected the key command to be recognized and activate after updating PHP to 7.4.3

**Debug Output**
[15:33:57.909] Logging Started...
[15:34:17.012] Calculate Anything[Script Filter] Queuing argument ''
[15:34:17.156] Calculate Anything[Script Filter] Script with argv '' finished
[15:34:17.160] ERROR: Calculate Anything[Script Filter] Code 255: Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.5". You are running 7.1.33. in /Users/mrevtai/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.15C4934D-D2BB-4417-959F-1536219C752D/vendor/composer/platform_check.php on line 24
[15:34:17.161] ERROR: Calculate Anything[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.5". You are running 7.1.33. in /Users/mrevtai/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.15C4934D-D2BB-4417-959F-1536219C752D/vendor/composer/platform_check.php on line 24

**System information:**
 - OS: macOS Mojave 10.14.6
 - Alfred Version 4.6.7 [1305]
- PHP Version 7.4.3 (upgraded and symlinked through Brew)

**Additional context**
I was prompted to update the workflow automatically by Alfred. Had full functionality with valid API Key before update.

<img width="623" alt="alfred-calculate-workflow-command" src="https://user-images.githubusercontent.com/17998319/177886664-bfd61dbb-0fd7-45ef-aff2-4f25adace0c1.png">

<img width="697" alt="macos-terminal-php-verified" src="https://user-images.githubusercontent.com/17998319/177886036-c4c460eb-e93b-4355-bc42-56d0589b96e5.png">

<img width="1138" alt="calcuate-workflow-debug" src="https://user-images.githubusercontent.com/17998319/177886183-ed8c7011-5435-4f7f-b0a8-4c4079664573.png">

**Comment by biati-digital** [comment]
Hi @mrevtai, this issue is not related to the workflow, even if you updated PHP, Alfred is still using your old version 7.1, the workflow can not do anything about this. I'm not sure if this can be configured in Alfred or what's the best way to tell Alfred to use a specific PHP version. You might be able to find more help in the Alfred forum.

**Comment by mrevtai** [comment]
Hello again, this is a bit frustrating that you closed out my issue rather quickly. Something clearly changed in the workflow itself. If I re-install version 3.2.0, the workflow functions again in Mojave. If I install any version after 3.2.0, it breaks. I am trying to figure out what in the workflow was changed going beyond version 3.2.0. I could not find any changelog notices or updates that specify a minimum macOS version per different versions of the workflow.

**Comment by biati-digital** [comment]
Hi @mrevtai i understand but like i said, the problem is not with the workflow and it does not require a minimum OS version, i closed the issue for several reasons, most of the time users do not reply back, like 95% of the issues are about PHP or brew which i do not provide support for.

Alfred 4.6 will search automatically for the PHP bin path, you are on Mojave so Alfred uses the default PHP included with your OS and ignores your update. The workflow will evolve and the dependencies will required and updated PHP version, PHP 7.1 is like 6 years old. There's no problem with that because even if you are on Mojave you can run `brew upgrade php` and get the latest version but again Alfred will not use it. so basically i've to choose between using dependencies with new code or invest more time in the workflow to make it work in every possible situation.

I'm also frustrated because like is said, seems like every single problem that comes up is because the user has problems with PHP or Brew, to be honest this is something Alfred should have solved when Apple removed PHP, Python, etc. A simple option to let the user choose the PHP binary should be enough. Apple notified about this like 2 years ago but still users have to manually install this kind of dependencies and no way to select a specific version.

Alfred recently release v5, i'll see if i can remove composer. The workflow itself does not require a specific PHP version (i think it will also work with PHP 5.6) but a dependency can define a specific version. 

I'll let you know when the update is ready and if i was able to remove composer.
