### ISSUE TITLE
How to enter values less that 1? For example 1/8" (i.e. one eight of an inch)

### ISSUE THREAD

**Issue by Stickyhavr** [biati-digital/alfred-calculate-anything#79]
Hello,
LOVE LOVE LOVE your workflow. Use it all the time.

I ran into an issue where I was trying to find out what 1/8" (one eighth of an inch) is in mm and no matter how I typed it, I couldn't seem to get CA to recognize it. Then I noticed I was having trouble with anything that was less than 1. 

Is there a way to convert one eighth, or 5/16ths of an in to mm. Or half an ounce to ml, or grams etc. etc. ? Sorry if this was in the documentation somewhere, I did read through the readme and searched closed issues but didn't see the answer if it was there.

Thanks!

**Comment by arvidbjorkstrom** [comment]
Using decimal numbers should work. Entering `0.125in mm` should give you 1/8 inches in mm.

An easy way to get the decimal value of 1/8 or 5/16 is to just write that in Alfred. The built in calculator should give you a decimal number. If you press enter that number will be copied to your clipboard and you can enter it again together with units to use the unit conversion. One thing to look out for is that if Alfreds calculator will use your system default number format so instead of `0.125` you might get `0,125` and that will not work with Calculate Anything yet (I've got a [pull request](https://github.com/biati-digital/alfred-calculate-anything/pull/94) waiting though :)

**Comment by Stickyhavr** [comment]
Great, thanks so much.
