### ISSUE TITLE
Cryptocurrency to currency PLN conversion bug

### ISSUE THREAD

**Issue by AAWO** [biati-digital/alfred-calculate-anything#99]
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?**
Yes

**Describe the bug**
The workflow uses Pollen cryptocurrency (https://coinmarketcap.com/currencies/pollen/) instead of Polish zloty (both use code PLN) for conversion from cryptocurrency (e.g. BTC). Conversion from fiat currency (e.g. USD) to PLN (Polish zloty) works correctly.

**To Reproduce**
1. Open Alfred 
1. Type '1 btc to pln'
2. The output value is completely different to the value from https://coinmarketcap.com/currencies/bitcoin/ (set the currency to 'PLN' in upper right corner)

**Expected behavior**
The output value should match the value from https://coinmarketcap.com/currencies/bitcoin/ (set the currency to 'PLN' in upper right corner).

**System information:**
 - OS: MacOS 13.2.1
 - Alfred Version 5.0.6
 - Calculate Anything - v3.5.0

**Comment by biati-digital** [comment]
Well this is not a bug exactly, if you enter `1 btc to pln` the workflow does the conversion correctly as it finds a crypto with the the same code `pln`, the same if you enter `100usd to pln` the conversion is done correctly. The issue is that the workflow does not now if you are trying to convert to crypto Pollen `pln` or to Polish zloty that uses the same code `pln`

The only think i can think of is to display multiple results in cases where the code is duplicated, for example entering `1 btc to pln` should return 2 results, the first a conversion to Pollen and the second a conversion to Polish zloty.

This can be a little complex so i'll mark this as feature request for now and i'll take a look when i've some time.

**Comment by AAWO** [comment]
That makes sense. Thanks for the explanation.

Maybe a list of ignored cryptocurrencies would be quicker to implement?

**Comment by biati-digital** [comment]
That wont work. 

For this to work it requires the two tools to work between them so additional checks must be performed, even with that it seems that if you type  `1 btc to pln` (Polish zloty) you'll probably get a different result from coinmarketcap as their API has limited fiat codes https://coinmarketcap.com/api/documentation/v1/#section/Standards-and-Conventions and `PLN` is not included so the workflow must use the Fixer API to get the rates.

**Comment by biati-digital** [comment]
This was added the latest version [4.0.0](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.0). Please read the release to see what's new.

Like i mentioned before, the coinmarketcap API has limited fiat codes, does not includes PLN and many others that this workflow supports so it works in conjunction with the other API's (fixer or exchangeratehost) to provide the conversion.

![CleanShot 2023-03-19 at 02 13 48](https://user-images.githubusercontent.com/1219228/226162368-89ac4f15-1903-4d31-ba97-07d3a24932cd.png)
